### ISSUE TITLE
geocode.sql contains harcoded path to missing file

### ISSUE THREAD

**Issue by clhenrick** [aepyornis/dob-jobs-parser#1]
Hey Ziggy,

It would be helpful (and necessary for others to use the code) to include the file (or a script on how to create it) that you mention in this line of `geocode.sql` with the repo:
https://github.com/aepyornis/dob-jobs-parser/blob/master/sql/geocode.sql#L16

Nice work

**Comment by aepyornis** [comment]
You can grab a copy of that file here if you need it: https://github.com/aepyornis/hpd/blob/master/bbl_lat_lng.txt

But I'm actually planning on removing that script and geocoding from this repo.  

This parser isn't new, fyi, it's from this project: https://github.com/aepyornis/DOB-Jobs -- I've just recently separated it out into it's own repo so it can be more accessible on it's own.

**Comment by clhenrick** [comment]
Great, thanks for the info.

-Chris
clhenrick.io
